# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  ZhangKong.Cloud
subtitle: 
name: ZhangKong 
email: zhangkong828@gmail.com
description: 本站是ZhangKong.Cloud的技术分享博客。
keywords: 生活故事,架构,大数据,一线,开发者,编程,代码,开源,IT网站,Developer,Programmer,Coder,Geek,IT技术博客,.Net,C#,.Net Core,Python,
encoding: "utf-8"
favicon: favicon.ico 

repository: zhangkong828/zhangkong828.github.io
github_url: https://github.com/zhangkong828
url: https://zhangkong.cloud
enforce_ssl: zhangkong.cloud

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

# Pagination
paginate: 12
paginate_path: 'page:num'

# Navigation. top menu list
menus:
  # -
  #   href: /link
  #   label: 友链
  #   target: _self

  # -
  #   href: /about
  #   label: 关于
  #   target: _self

# Navigation. main menu list
navs:

  -
    href: /
    label: 首页

  # -
  #   href: /spring-boot.html
  #   label: Spring Boot
  #   target: _self
  #   subnav:

  #     -
  #       subHref: /spring-boot.html
  #       subLabel: Spring Boot

  #     -
  #       subHref: /spring-cloud.html
  #       subLabel: Spring Cloud
  -
    href: /archives
    label: 归档
    target: _self

  -
    href: /open-source
    label: 开源

  -
    href: /link
    label: 友链
    target: _self

  -
    href: /about
    label: 关于
    target: _self


# labels. my blog key words
labels:
  # -
  #   href: /open-source.html
  #   label: Code  
  #   target: _blank



# selected articles
classes:

  # -
  #   href: /cartoon.html
  #   name: 不会笑青年
  #   describe: 内心沉稳 ，放荡不羁。

  # -
  #   href: /life.html
  #   name: 我的故事
  #   describe: 生活就是故事，故事就是生活

  # -
  #   href: /it.html
  #   name: IT行业深度报道
  #   describe: IT大佬，互联网知名公司的故事




# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show

# Google Analytics
# analytics :
# provider : google
#   google :
#     tracking_id : ''  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, MySQL, Oracle, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, NodeJS, ExpressJS, MongoDB, Redis, PHP,  Boostrap]
skill_mobile_app_keywords: [vuejs, hyhird app]


# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: zhangkong
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: zhangkong828
    repo: blog-comments
    oauth:
        client_id: 54a94d050e1e2b420f30
        client_secret: c22e87c1b2ef30c21ead785c00ed223bc6e98f28
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: zhangkong828
    repo: blog-comments
    clientID: 54a94d050e1e2b420f30
    clientSecret: c22e87c1b2ef30c21ead785c00ed223bc6e98f28
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false